# Generated by Django 5.0.2 on 2024-02-17 06:50

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('cover_image', models.ImageField(blank=True, default=None, upload_to='')),
                ('price', models.FloatField()),
                ('discount_percent', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('end_of_discount', models.DateField(default=django.utils.timezone.now)),
                ('genre', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=70)),
                ('amount', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Gamer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('gamer_first_name', models.CharField(blank=True, max_length=50)),
                ('gamer_last_name', models.CharField(blank=True, max_length=150)),
                ('gamer_email', models.EmailField(blank=True, max_length=254)),
                ('gamer_password', models.CharField(max_length=100)),
                ('birth_date', models.DateField(blank=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend', to='egames.gamer')),
                ('gamer', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='gamer', to='egames.gamer')),
            ],
        ),
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egames.game')),
                ('gamer', models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='egames.gamer')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egames.game')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egames.gamer')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('comment', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egames.game')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egames.gamer')),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egames.game')),
                ('gamer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egames.gamer')),
            ],
        ),
    ]
