# Generated by Django 5.0.2 on 2024-02-17 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='end_of_discount',
            field=models.DateField(auto_now_add=True),
        ),
    ]
