# Generated by Django 5.0.2 on 2024-02-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genre',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='review',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
