# Generated by Django 5.0.2 on 2024-02-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egames', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='wallet',
            field=models.FloatField(default=0),
        ),
    ]
