# Generated by Django 5.0.2 on 2024-02-25 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egames', '0002_gamer_wallet'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='discount_price',
            new_name='final_price',
        ),
        migrations.RemoveField(
            model_name='game',
            name='end_of_discount',
        ),
    ]
