# Generated by Django 5.0.2 on 2024-02-17 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egames', '0003_role_remove_game_genre_genre_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='amount',
        ),
    ]
