# Generated by Django 5.0.2 on 2024-02-26 04:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egames', '0003_rename_discount_price_game_final_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='egames.gamer'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='gamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='egames.gamer'),
        ),
    ]
