# Generated by Django 5.0.2 on 2024-02-19 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('egames', '0003_alter_gamer_birth_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamer',
            name='birth_date',
        ),
    ]
