# Generated by Django 5.0.2 on 2024-02-29 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egames', '0004_alter_friend_friend_alter_friend_gamer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='egames.role'),
        ),
    ]
