# Generated by Django 5.0.2 on 2024-02-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egames', '0004_remove_gamer_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamer',
            name='birth_date',
            field=models.DateField(default=None, null=True),
        ),
    ]
